#server.port=8181 ???????

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /myapi.html

# database connection
spring :
  datasource:
    url: jdbc:mariadb://localhost:3306/demodb
    username: root
    password: mariadb

  jpa:
    database: mysql #실제 사용할 dbms 지정
#    database-platform: org.hibernate.dialect.Oracle10gDialect #방언 설정
    database-platform: org.hibernate.dialect.MariaDB106Dialect #방언 설정
    hibernate:
      database: mysql # 실제사용할 dbms 지정
      generate-ddl: true # 각 DBMS에 맞는 고유 기능을 사용할 지의 여부
      ddl-auto: update # ddl문을 처리할 떄 설정
    show-sql: true
    generate-ddl: true #각 dbms에 맞는 고유 기능을 사용할 지 여부
    properties:
      hibernate:
        format_sql: true

# create : 매 실행마다 ddl을 재실행
# update : 매 실행마다 바뀐 부분의 ddl을 ALTAR문으로 수정
# none : ddl을 실행하지 않음
#
#spring:
#  h2:
#    console:
#      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
#      path: /h2-console  # H2 Console? Path
#    # Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
#    datasource:
#      driver-class-name: org.h2.Driver  # Database? H2? ?????.
#      url: jdbc:h2:tcp://localhost/~/test  # H2 ?? ??
#      username: sa  # H2 ?? ? ??? username ?? (??? ??? ??)
#      password:  # H2 ?? ? ??? password ?? (??? ??? ??)
#
#
#mybatis:
#  configuration:
#    multiple-result-sets-enabled: false
#    map-underscore-to-camel-case: true
#    call-setters-on-nulls: true
#    jdbc-type-for-null: varchar
#    default-fetch-size: 500
#  mapper-locations:
#    - classpath:mybatis/mapper/*.xml

logging:
  level:
    root: debug #???? info? trace? debug??
    com:
      example:
        apibasic:
          req: trace
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정

#
#spring:
#  datasource:
#    url:
#    username:sa
#    password:
